### PR TITLE
Created User Class

### PR DESCRIPTION
**Pull request by rajkumarm23**
Hi TeamLead,

I have created the User model with two properties, please check and confirm.

Thanks,
Rajkumar

### CODE REVIEW

**Comment by RajkumarMekala23** [comment]
Hi Rajkumar,

Add one more property like password in the User class.

Thanks,
TL

**Comment by rajkumarm23** [comment]
Hi TL,

I have added the password property in the User Class. Please check

Thanks,
Rajkumar

**Comment by RajkumarMekala23** [comment]
Hi Raj,

Ur code everything looks good, please go ahead with merge from testing to master.

Thanks
TL

**Comment by RajkumarMekala23** [comment]
merge code from testing to master

**Pull request merged**
